# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

r_packages:
  - covr
  - roxygen2

r_github_packages:
  - krlmlr/staticdocs@devel

after_success:
  - Rscript -e 'covr::codecov()'
  - scripts/deploy-pages.sh

notifications:
  email:
    on_success: change
    on_failure: change
